apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: ibmcloudmachineproviderspecs.ibmcloud.cluster.k8s.io
spec:
  group: ibmcloud.cluster.k8s.io
  names:
    kind: IbmcloudMachineProviderSpec
    plural: ibmcloudmachineproviderspecs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        dataCenter:
          type: string
        domain:
          type: string
        hostname:
          type: string
        hourlyBillingFlag:
          type: boolean
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        localDiskFlag:
          type: boolean
        maxMemory:
          format: int64
          type: integer
        metadata:
          type: object
        osReferenceCode:
          type: string
        sshKeyName:
          type: string
        startCpus:
          format: int64
          type: integer
        userDataSecret:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
