[book]
authors = ["The Cluster API Provider IBM Cloud Maintainers"]
language = "en"
multilingual = false
src = "src"
title = "Kubernetes Cluster API Provider IBM Cloud"

[output.html]
curly-quotes = true
git-repository-url = "https://sigs.k8s.io/cluster-api-provider-ibmcloud"

[preprocessor.tabulate]
command = "mdbook-tabulate"

[preprocessor.embed]
command = "mdbook-embed"

[preprocessor.releaselink]
command = "mdbook-releaselink"
