apiVersion: ibmcloud.cluster.k8s.io/v1alpha1
kind: IbmcloudClusterProviderSpec
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ibmcloudclusterproviderspec-sample
spec:
  # Add fields here
  foo: bar
