apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: IBMPowerVSMachine
metadata:
  name: ibmpowervsmachine-sample
spec:
  image:
    name: capibm-powervs-centos-8-1-22-4
  memory: "8"
  network:
    name: capi-test-3
  procType: shared
  processors: "0.25"
  serviceInstanceID: 7845d372-d4e1-46b8-91fc-41051c984601
  sshKey: sample-pub-key
  sysType: s922
