apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
- rbac/rbac_role.yaml
- rbac/rbac_role_binding.yaml
- rbac/auth_proxy_service.yaml
- rbac/auth_proxy_role.yaml
- rbac/auth_proxy_role_binding.yaml
- crds/ibmcloud_v1alpha1_ibmcloudclusterproviderspec.yaml
- crds/ibmcloud_v1alpha1_ibmcloudclusterproviderstatus.yaml
- crds/ibmcloud_v1alpha1_ibmcloudmachineproviderspec.yaml
- crds/ibmcloud_v1alpha1_ibmcloudmachineproviderstatus.yaml
